# Generated by Django 4.0.6 on 2022-07-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_db', '0001_initial'),
        ('news_app', '0002_remove_post_category_delete_category_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news_db.category')),
            ],
            bases=('news_db.category',),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news_db.post')),
            ],
            bases=('news_db.post',),
        ),
    ]
