# Generated by Django 4.0.6 on 2022-08-08 09:25

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_db', '0001_initial'),
        ('news_app', '0004_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalUser',
            fields=[
                ('localuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news_db.localuser')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('news_db.localuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
